[package]
name = "autocharger"
version = "0.1.0"
edition = "2021"

[dependencies]
battery = "0.7.8"
reqwest = "0.12.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.20.0", features = ["full"] }
tokio-macros = "2.3.0"